name: Your New Jekyll Site
markdown: redcarpet
pygments: true


####### For local access with http://localhost:4000/ #######
# baseurl:     

####### For local access with http://localhost:4000/blog/ #######
####### For access with http://lightgao.github.io/blog/ #######
baseurl:     /blog
