name: Your New Jekyll Site
markdown: redcarpet
pygments: true

######## FOR LOCAL TEST ############
# baseurl:
# url:         http://localhost:4000

######## FOR PUSH TO GITHUB PAGE ##########
baseurl:     /blog
# url:         http://lightgao.github.io
